name: Add UUID to New Files

on:
  push:
    branches:
      - master  # Modifie selon la branche sur laquelle tu veux que l'action se déclenche

jobs:
  add_uuid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for new files and add UUID to frontmatter
        run: |
          IFS=$'\0'
          new_files=()
          while IFS= read -r -d $'\0'; do
            new_files+=("$REPLY")
          done < <(git diff --find-renames --name-only --diff-filter=A -z HEAD~1)
          unset IFS

          echo "Fichiers ajoutés lors du dernier commit:"
          echo "$new_files"

          for file in "${new_files[@]}"; do
            echo "Vérification du fichier: $file"
            # Vérifie si le fichier a un frontmatter (typique des fichiers Markdown)
            if [[ "$file" == *.md || "$file" == *.markdown ]]; then
              echo "Fichier Markdown détecté: $file"
            
              # Génère un UUID
              uuid=$(uuidgen)
            
              # Vérifie la présence d'un frontmatter YAML
              if grep -q "^---" "$file"; then
                echo "Frontmatter détecté."
            
                # Vérifie si un uuid est déjà présent
                if ! grep -q "^uuid:" "$file"; then
                  # Ajoute l'UUID après le premier ---
                  sed -i "0,/---/s/---/---\nuuid: $uuid/" "$file"
                  echo "UUID ajouté au frontmatter du fichier: $file"
                else
                  echo "UUID déjà présent dans le fichier: $file"
                fi
              else
                echo "Pas de frontmatter trouvé. Ajout d'un frontmatter."
                # Ajoute un frontmatter complet avec UUID au début du fichier
                tmpfile=$(mktemp)
                {
                  echo "---"
                  echo "uuid: $uuid"
                  echo "---"
                  cat "$file"
                } > "$tmpfile"
                mv "$tmpfile" "$file"
                echo "Frontmatter avec UUID ajouté en tête du fichier: $file"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Vérifie s'il y a des modifications à commit
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Add UUID to new files [skip ci]"  # Message pour éviter le déclenchement en boucle
            git push
          fi

#      - name: Update the files
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: "Add UUID to new files [skip ci]"
#          file_pattern: "."
#          status_options: '--untracked-files=no'
#
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ env.REF }}
